### ISSUE TITLE
Docker-compose support

### ISSUE THREAD

**Issue by bttd** [traccar/traccar-docker#101]
Hi,

It is possible to provide an official docker-compose file to run this docker?

**Comment by sincze** [comment]
Depends on your needs.
An example with traccar + separate MariaDB.

`version: '2.4'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    image: yobasystems/alpine-mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      TZ: Europe/Amsterdam
      #MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: <root_password>
      MYSQL_DATABASE: <username>
      MYSQL_USER: <username>
      MYSQL_PASSWORD: <password>
    ports:
      - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PA$
      interval: 60s
      timeout: 5s
      retries: 5
      #start_period: 30s
    networks:
    - Iot

  traccar:
    container_name: traccar
    hostname: traccar
    restart: unless-stopped
    image: traccar/traccar:4.15-ubuntu
    ports:
    - 5002:5002/tcp
    - 5002:5002/udp
    - 82:8082
    volumes:
     - ./traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml
     - ./traccar/logs:/opt/traccar/logs:rw
    depends_on:
      - mariadb
    networks:
    - Iot

networks:
  Iot:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.1.0/29
`

**Comment by nodecentral** [comment]
Many thanks for sharing the Docker compose, I’m still learning Docker would you be able to explain the `networks` part at the bottom ? I’d like my instance to be on the same local network (LAN) as all my other devices which is 192.168.1.1 ? Do I simply change the IP ?

**Comment by sincze** [comment]
No problem.  Great you liked it. That is why I share to help others!

I think the DB was created automatically, but it was some time ago.  Can do a check if you want on a spare docker machine.

**Comment by ippocratis** [comment]
Yeah I actually thought that docker-compose should create user and database
My networking databases and docker knowledge is pretty basic though
And I tried many things to spin up the containers 

(My issue is here https://github.com/traccar/traccar-docker/issues/103#issuecomment-133708941)

So its likely that I miss estimated things

**Comment by nodecentral** [comment]
Hi @ippocratis 

By any chance, is there an updated compose file you could post?

Also, as I want to have this instance on the same network as my primary LAN, do I just change the ip4 subnet to my ip, e.g. 192.168.1.1/29 ?

**Comment by ippocratis** [comment]
@nodecentral 

docker network ls
verify the the network name as.provided in the docker-compose is running  for example traccar-trc

`docker network inspect traccar_trc`

under "Name": "traccar_trc",we need "Subnet": "192.168.112.0/20"

and under "traccar-db",
we need "IPv4Address": "192.168.112.2/20",

subnet goes to 

 config:
        - subnet: 192.168.112.0/20
in docker-compose

and

IPv4Address goes to
 `jdbc:mysql://192.168.112.2:3306/traccar-db`

 in /opt/traccar/conf/traccar.xml:ro


So you will actually use the docker internal bridge ip's not the host

**Comment by ippocratis** [comment]
@nodecentral 

docker network ls
verify the the network name as.provided in the docker-compose is running  for example traccar-trc

`docker network inspect traccar_trc`

under "Name": "traccar_trc",we need "Subnet": "192.168.112.0/20"

and under "traccar-db",
we need "IPv4Address": "192.168.112.2/20",

subnet goes to 

 config:
        - subnet: 192.168.112.0/20
in docker-compose

and

IPv4Address goes to
 `jdbc:mysql://192.168.112.2:3306/traccar-db`
Like `jdbc:mysql://docker-bridge-ipv4:container-unstrap-port/database-name`

 in /opt/traccar/conf/traccar.xml:ro


So you will actually use the docker internal bridge ip's not the host

**Comment by ippocratis** [comment]
> @nodecentral
> 
> docker network ls verify the the network name as.provided in the docker-compose is running for example traccar-trc
> 
> `docker network inspect traccar_trc`
> 
> under "Name": "traccar_trc",we need "Subnet": "192.168.112.0/20"
> 
> and under "traccar-db", we need "IPv4Address": "192.168.112.2/20",
> 
> subnet goes to
> 
> config: - subnet: 192.168.112.0/20 in docker-compose
> 
> and
> 
> IPv4Address goes to `jdbc:mysql://192.168.112.2:3306/traccar-db` Like `jdbc:mysql://docker-bridge-ipv4:container-internal-port/database-name`
> 
> in /opt/traccar/conf/traccar.xml:ro
> 
> So you will actually use the docker internal bridge ip's not the host
> 
> My docker-compose is no diferent than what @sincze provided
> 
> I just used the debian arm64 image instead of Ubuntu
> 
> in traccar hostname I used my ddns domain name which I use to access traccar from outside my lan
> 
> Added command: --default-authentication-plugin=mysql_native_password as I want yo add user/db
> 
> and added MYSQL_DATABASE=, MYSQL_USER= , MYSQL_PASSWORD= all to traccar-db environment together with MYSQL_ROOT_PASSWORD=
> 
> All with trial and error

The compose.yml for reference

```
version: "3"

services:
    traccar-db:
        image: yobasystems/alpine-mariadb
        container_name: traccar-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - /run/media/ippo/TOSHIBA/traccar/mysql-data:/var/lib/mysql
            - /run/media/ippo/TOSHIBA/traccar/mysql:/etc/mysql/conf.d
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=xxx
            - MYSQL_DATABASE=traccar-db
            - MYSQL_USER=xxx
            - MYSQL_PASSWORD=xxx
        networks:
            - trc2
            - 
    traccar:
        image: traccar/traccar:debian
        hostname: XXX.XXX.com
        container_name: traccar
        depends_on:
           - traccar-db
        restart: always
        volumes:
            - /run/media/ippo/TOSHIBA/traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
            - /run/media/ippo/TOSHIBA/traccar/logs:/opt/traccar/logs:rw
        ports:
            - "5055:5055"
            - "82:8082"
        networks:
            - trc2
            - 
networks:
  trc2:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.112.0/20

volumes:
   mysql-data:
   mysql:
   logs:
 ```
