### ISSUE TITLE
Docker-compose path/fiile problem. "Are you trying to mount a directory onto a file?"

### ISSUE THREAD

**Issue by Vinestou** [traccar/traccar-docker#104]
Im using Docker-compose to run Traccar and I am having difficulty getting this to work. I want to map the traccar.xml file and not he folder but when I add path to the compose file I get an error that its a directory.

compose file:
 ```
version: '3.8'
services:
  traccar:
    container_name: traccar
    hostname: traccar
    image: traccar/traccar:latest
    depends_on: ["db"]
    environment:
       MYSQL_HOST: db
       MYSQL_ROOT_PASSWORD: traccar
       MYSQL_DATABASE: traccar
       MYSQL_USER: traccar
       MYSQL_PASSWORD: traccar
    restart: unless-stopped
    ports:
      - '8082:8082/tcp'
      - '5013:5013/tcp'
      - '5013:5013/udp'
      - '5015:5015/tcp'
      - '5015:5015/udp'
      - '5093:5093/tcp'
      - '5093:5093/udp'
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro


  db:
    image: mysql:8.0.20
    container_name: traccar-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: traccar
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: traccar
```

I get the following error.

> ERROR: for traccar  Cannot start service traccar: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/collision/docker/traccar/conf/traccar.xml" to rootfs at "/opt/traccar/conf/traccar.xml": mount /home/collision/docker/traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
