### ISSUE TITLE
I am not getting any logs for my traccar dokcer that I deployed to my eks cluster. 

### ISSUE THREAD

**Issue by ssshreyans26** [traccar/traccar-docker#138]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traccar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traccar
  template:
    metadata:
      labels:
        app: traccar
    spec:
      containers:
      - name: traccar
        image: ********.dkr.ecr.ap-south-1.amazonaws.com/test-traccar:new # Replace with your custom image
        ports:
        - name: web
          containerPort: 8082 # Traccar web interface
        - name: device-tcp
          containerPort: 5000 # Device communication (TCP)
        - name: device-udp
          containerPort: 5000 # Device communication (UDP)
          protocol: UDP
        - name: device-tcp-5150
          containerPort: 5150 # Extend ports as needed for devices (TCP)
        - name: device-udp-5150
          containerPort: 5150 # Extend ports as needed for devices (UDP)
          protocol: UDP
        env:
        - name: TRACCAR_DATABASE_URL
          value: "jdbc:mysql://<amazon-rds>:3306/traccar"
        - name: TRACCAR_DATABASE_USER
          value: "****"
        - name: TRACCAR_DATABASE_PASSWORD
          value: "****"
---
apiVersion: v1
kind: Service
metadata:
  name: traccar-service
spec:
  selector:
    app: traccar
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8082 # Expose Traccar web UI on port 80
    - name: device-tcp
      protocol: TCP
      port: 5000 # Expose device communication (TCP)
      targetPort: 5000
    - name: device-udp
      protocol: UDP
      port: 5000 # Expose device communication (UDP)
      targetPort: 5000
    - name: device-tcp-5150
      protocol: TCP
      port: 5150 # Expose device communication (TCP)
      targetPort: 5150
    - name: device-udp-5150
      protocol: UDP
      port: 5150 # Expose device communication (UDP)
      targetPort: 5150
  type: ClusterIP # or NodePort if not using a cloud provider
```
  
  
  I am using the below commands to create my ecr image :
  
  
```
FROM traccar/traccar:latest
COPY traccar_1.xml /opt/traccar/conf/traccar.xml
```

`docker buildx build --platform linux/amd64 -t *****.dkr.ecr.ap-south-1.amazonaws.com/test-traccar:new --push .\n`

When I am trying to port forward the web port from lens nothing is coming up, 
"This site can’t be reached localhost refused to connect."

There is nothing in the logs, I tried checking /opt/traccar/logs as well, this is the log :
`2024-09-12 06:09:38  INFO: Operating system name: Linux version: 5.10.223-212.873.amzn2.x86_64 architecture: amd64
2024-09-12 06:10:44  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Alpine version: 17.0.12+7-alpine-r0
2024-09-12 06:10:45  INFO: Memory limit heap: 1024mb non-heap: 0mb
2024-09-12 06:10:47  INFO: Character encoding: UTF-8
2024-09-12 06:10:49  INFO: Version: 6.4
2024-09-12 06:10:49  INFO: Starting server...
2024-09-12 06:15:08  INFO: HikariPool-1 - Starting...`
<img width="1395" alt="Screenshot 2024-09-12 at 11 48 38 AM" src="https://github.com/user-attachments/assets/d98a35c6-f203-4085-868b-77117145b2d3">

It is also getting terminated after sometime with error :
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown

terminated
Reason:Reason: Error - exit code: 1
Started at: 2024-09-12T11:22:02+05:30
Finished at: 2024-09-12T11:54:12+05:30
