### ISSUE TITLE
Increasing JVM memory size and other optimizations

### ISSUE THREAD

**Issue by jike212** [traccar/traccar-docker#20]
As I look at some of the optimizations [mentioned here](https://www.traccar.org/optimization/), I see a number of ways to help incorporate them into Docker.

Is there way to make some of these optimizations through the Dockerfile? (e.g. turning the JVM size into an environment variable, etc.)

**Comment by magna-z** [comment]
I don`t like any wrappers for application in docker container because there are often errors in the transmission of the system signal and this is not explicit. Therefore is used `ENTRYPOINT ["java", "-Xms512m", "-Xmx512m", "-Djava.net.preferIPv4Stack=true"]` and `CMD ["-jar", "tracker-server.jar", "conf/traccar.xml"]`.
For set limits with docker run use the arg `--ulimit` and for increase JVM heap size `docker run ... --entrypoin java ... traccar/traccar:4.0 -Xms2g -Xmx2g -Djava.net.preferIPv4Stack=true -jar", "tracker-server.jar", "conf/traccar.xml`.

Example with docker-compose.yml:
```
version: '3'
services:
  traccar:
    image: traccar/traccar:4.0
    entrypoint:
    - java
    - -Xms2g
    - -Xmx2g
    - -Djava.net.preferIPv4Stack=true
    volumes:
    ...
    ports:
    ...
    ulimits:
      nproc: 65535
      nofile:
        soft: 50000
        hard: 50000
    ...
```

**Comment by delatitude** [comment]
After running my docker compose, the container keeps restarting. Here is my docker-compose file. 

```
version: '3'
services:
  traccar:
    image: "traccar/traccar:latest"
    restart: always
    entrypoint:
      - java
      - -Xms2g
      - -Xmx2g
      - -Djava.net.preferIPv4Stack=true    
    ports:
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
      - "8082:8082"
    volumes:
      - "/data/traccar/logs:/opt/traccar/logs:rw"
      - "/data/traccar/data:/opt/traccar/data:rw"
      - "/root/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ulimits:
      nproc: 65535
      nofile:
        soft: 50000
        hard: 50000      
```
