### ISSUE TITLE
Docker compose - not working - keeps restarting container.

### ISSUE THREAD

**Issue by delatitude** [traccar/traccar-docker#25]
After running my docker compose, the container keeps restarting. Here is my docker-compose file. 
Am i doing something incorrect. Please advice.

```
version: '3'
services:
  traccar:
    image: "traccar/traccar:latest"
    restart: always
    entrypoint:
      - java
      - -Xms2g
      - -Xmx2g
      - -Djava.net.preferIPv4Stack=true    
    ports:
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
      - "8082:8082"
    volumes:
      - "/data/traccar/logs:/opt/traccar/logs:rw"
      - "/data/traccar/data:/opt/traccar/data:rw"
      - "/root/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ulimits:
      nproc: 65535
      nofile:
        soft: 50000
        hard: 50000      
```
